spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/travel
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

integration:
  invoice:
    url: https://invoice.com